sonar.projectKey=financial-reports-functions
sonar.projectName=Financial Reports Functions

sonar.sourceEncoding=UTF-8

sonar.sources=.

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/test-results/**,\
  **/*.spec.ts,\
  **/*.test.ts,\
  local-infra/**

sonar.tests=.
sonar.test.inclusions=\
  **/*.spec.ts,\
  **/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=\
  **/*.function.ts
