sonar.projectKey=financial-reports-functions
sonar.projectName=Financial Reports Functions

sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=\
  **/*.spec.ts

sonar.exclusions=\
  **/*.spec.ts,\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/test-results/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=\
  src/functions/**/*.function.ts,\
  **/index.ts,\
  **/*.types.ts,\
  **/*.command.ts,\
  **/*.query.ts,\
  **/*.result.ts,\
  **/*.integration-event.ts,\
  **/*.repository.ts,\
  **/*.publisher.ts,\
  **/*.generator.ts,\
  **/*.storage.ts,\
  **/*.http.ts
