sonar.projectKey=financial-reports-functions
sonar.projectName=Financial Reports Functions

sonar.sourceEncoding=UTF-8

# ------------------------------------------------------------
# Analysis scope
# ------------------------------------------------------------

sonar.sources=src
sonar.tests=src

sonar.exclusions=\
  src/**/tests/**,\
  **/*.spec.ts

sonar.test.inclusions=\
  src/**/tests/**/*.spec.ts,\
  **/*.spec.ts

# ------------------------------------------------------------
# Coverage
# ------------------------------------------------------------

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=\
  src/functions/**/*.function.ts,\
  **/index.ts,\
  **/*.types.ts,\
  **/*.command.ts,\
  **/*.query.ts,\
  **/*.result.ts,\
  **/*.integration-event.ts,\
  **/*.repository.ts,\
  **/*.publisher.ts,\
  **/*.generator.ts,\
  **/*.storage.ts,\
  **/*.http.ts
