trigger: none

pr: none

name: azure-function-dev-$(Date:yyyyMMdd).$(Rev:r)

stages:

  - template: ../templates/node-function-app.yml

    parameters:
      environmentName: 'dev'

      azureServiceConnection: '<AZURE-SERVICE-CONNECTION-DEV>'

      functionAppName: '<FUNCTION-APP-NAME-DEV>'

      nodeVersion: '24.x'

      buildCommand: 'npm run build:prod'

      buildOutput: 'dist'

      runTests: true

      runCoverage: false

      runSonar: false

      appType: 'functionAppLinux'

      runtimeStack: 'NODE|24'

      isFlexConsumption: false
