trigger: none

pr: none

name: azure-function-uat-$(Date:yyyyMMdd).$(Rev:r)

stages:

  - template: ../templates/node-function-app.yml

    parameters:
      environmentName: 'uat'

      azureServiceConnection: '<AZURE-SERVICE-CONNECTION-UAT>'

      functionAppName: '<FUNCTION-APP-NAME-UAT>'

      nodeVersion: '24.x'

      buildCommand: 'npm run build:prod'

      buildOutput: 'dist'

      runTests: true

      runCoverage: true

      runSonar: true

      coverageCommand: 'npm run test:coverage'

      coverageReportPath: 'coverage/lcov.info'

      sonarServiceConnection: '<SONARQUBE-SERVICE-CONNECTION>'

      sonarProjectKey: '<SONAR-PROJECT-KEY>'

      sonarProjectName: '<SONAR-PROJECT-NAME>'

      appType: 'functionAppLinux'

      runtimeStack: 'NODE|24'

      isFlexConsumption: false
