trigger: none

pr: none

name: cd-prd-$(Date:yyyyMMdd).$(Rev:r)


resources:
  pipelines:
    - pipeline: release
      source: '<CD-STG-PIPELINE-NAME>'
      trigger: true


stages:
  - stage: Deploy_PRD
    displayName: Deploy PRD

    jobs:
      - template: ../templates/deploy.yml

        parameters:
          environmentName: '<ENVIRONMENT-PRD>'
          azureServiceConnection: '<SERVICE-CONNECTION-PRD>'
          functionAppName: '<FUNCTION-APP-PRD>'
          artifactSource: 'release'
          publishArtifact: false
