trigger: none

pr: none

name: cd-stg-$(Date:yyyyMMdd).$(Rev:r)


resources:
  pipelines:
    - pipeline: release
      source: '<CD-UAT-PIPELINE-NAME>'
      trigger: true


stages:
  - stage: Deploy_STG
    displayName: Deploy STG

    jobs:
      - template: ../templates/deploy.yml

        parameters:
          environmentName: '<ENVIRONMENT-STG>'
          azureServiceConnection: '<SERVICE-CONNECTION-STG>'
          functionAppName: '<FUNCTION-APP-STG>'
          artifactSource: 'release'
          publishArtifact: true
