trigger: none

pr: none

name: cd-uat-$(Date:yyyyMMdd).$(Rev:r)


resources:
  pipelines:
    - pipeline: release
      source: '<CD-DEV-PIPELINE-NAME>'
      trigger: true


stages:

  - stage: Deploy_UAT
    displayName: Deploy UAT

    jobs:

      - template: ../templates/deploy.yml

        parameters:
          environmentName: '<ENVIRONMENT-UAT>'
          azureServiceConnection: '<SERVICE-CONNECTION-UAT>'
          functionAppName: '<FUNCTION-APP-UAT>'
          artifactSource: 'release'
          artifactName: 'function-app'
          packageFileName: 'function-app.zip'
          publishArtifact: true
