trigger:
  branches:
    include:
      - main

pr: none

name: function-dev-$(Date:yyyyMMdd).$(Rev:r)


parameters:
  - name: runTests
    displayName: Run tests
    type: boolean
    default: true

  - name: runCoverage
    displayName: Run coverage
    type: boolean
    default: false

  - name: runSonar
    displayName: Run SonarQube
    type: boolean
    default: false


stages:

  - stage: Build
    displayName: Build

    jobs:

      - template: ../templates/build.yml

        parameters:
          runTests: ${{ parameters.runTests }}

          runCoverage: ${{ parameters.runCoverage }}

          runSonar: ${{ parameters.runSonar }}

          buildCommand: 'npm run build:prod'

          testCommand: 'npm test'

          coverageCommand: 'npm run test:coverage'

          sonarServiceConnection: '<SONAR-SERVICE-CONNECTION>'

          sonarProjectKey: '<SONAR-PROJECT-KEY>'

          sonarProjectName: '<SONAR-PROJECT-NAME>'


  - stage: Deploy_DEV
    displayName: Deploy DEV

    dependsOn:
      - Build

    condition: succeeded()

    jobs:

      - template: ../templates/deploy.yml

        parameters:
          environmentName: '<ENVIRONMENT-DEV>'

          azureServiceConnection: '<SERVICE-CONNECTION-DEV>'

          functionAppName: '<FUNCTION-APP-DEV>'

          artifactSource: 'current'

          isFlexConsumption: false
