parameters:
  - name: environmentName
    type: string

  - name: azureServiceConnection
    type: string

  - name: functionAppName
    type: string

  - name: artifactSource
    type: string


jobs:

  - deployment: Deploy
    displayName: Deploy Azure Function App

    pool:
      vmImage: 'ubuntu-latest'

    environment:
      name: ${{ parameters.environmentName }}

    strategy:
      runOnce:
        deploy:
          steps:

            - download: none


            - ${{ if eq(parameters.artifactSource, 'current') }}:

                - download: current
                  artifact: function-app


                - task: AzureFunctionApp@2
                  displayName: Deploy Azure Function App

                  inputs:
                    azureSubscription: ${{ parameters.azureServiceConnection }}

                    appType: 'functionAppLinux'

                    appName: ${{ parameters.functionAppName }}

                    package: '$(Pipeline.Workspace)/function-app/function-app.zip'

                    deploymentMethod: 'auto'


            - ${{ if ne(parameters.artifactSource, 'current') }}:

                - download: ${{ parameters.artifactSource }}

                  artifact: function-app


                - task: AzureFunctionApp@2
                  displayName: Deploy Azure Function App

                  inputs:
                    azureSubscription: ${{ parameters.azureServiceConnection }}

                    appType: 'functionAppLinux'

                    appName: ${{ parameters.functionAppName }}

                    package: '$(Pipeline.Workspace)/${{ parameters.artifactSource }}/function-app/function-app.zip'

                    deploymentMethod: 'auto'
