parameters:
  - name: environmentName
    type: string

  - name: azureServiceConnection
    type: string

  - name: functionAppName
    type: string

  - name: artifactSource
    type: string

  - name: artifactName
    type: string
    default: 'function-app'

  - name: packageFileName
    type: string
    default: 'function-app.zip'

  - name: publishArtifact
    type: boolean
    default: false


jobs:
  - deployment: Deploy
    displayName: Deploy Azure Function App

    pool:
      vmImage: 'ubuntu-latest'

    environment:
      name: ${{ parameters.environmentName }}

    strategy:
      runOnce:
        deploy:
          steps:

            # Evita la descarga automática de todos los artifacts.
            - download: none


            # Artifact generado dentro del mismo pipeline.
            - ${{ if eq(parameters.artifactSource, 'current') }}:

                - download: current
                  artifact: ${{ parameters.artifactName }}


                - task: AzureFunctionApp@2
                  displayName: Deploy Azure Function App

                  inputs:
                    azureSubscription: ${{ parameters.azureServiceConnection }}

                    appType: 'functionAppLinux'

                    appName: ${{ parameters.functionAppName }}

                    package: '$(Pipeline.Workspace)/${{ parameters.artifactName }}/${{ parameters.packageFileName }}'

                    deploymentMethod: 'auto'


                - ${{ if eq(parameters.publishArtifact, true) }}:

                    - task: PublishPipelineArtifact@1
                      displayName: Promote release artifact

                      inputs:
                        targetPath: '$(Pipeline.Workspace)/${{ parameters.artifactName }}/${{ parameters.packageFileName }}'

                        artifact: ${{ parameters.artifactName }}


            # Artifact procedente del pipeline anterior.
            - ${{ if ne(parameters.artifactSource, 'current') }}:

                - download: ${{ parameters.artifactSource }}

                  artifact: ${{ parameters.artifactName }}


                - task: AzureFunctionApp@2
                  displayName: Deploy Azure Function App

                  inputs:
                    azureSubscription: ${{ parameters.azureServiceConnection }}

                    appType: 'functionAppLinux'

                    appName: ${{ parameters.functionAppName }}

                    package: '$(Pipeline.Workspace)/${{ parameters.artifactSource }}/${{ parameters.artifactName }}/${{ parameters.packageFileName }}'

                    deploymentMethod: 'auto'


                - ${{ if eq(parameters.publishArtifact, true) }}:

                    - task: PublishPipelineArtifact@1
                      displayName: Promote release artifact

                      inputs:
                        targetPath: '$(Pipeline.Workspace)/${{ parameters.artifactSource }}/${{ parameters.artifactName }}/${{ parameters.packageFileName }}'

                        artifact: ${{ parameters.artifactName }}
