parameters:
  - name: artifactName
    type: string
    default: 'function-app'

  - name: packageFileName
    type: string
    default: 'function-app.zip'

  - name: runSmokeTest
    type: boolean
    default: false

  - name: smokeTestCommand
    type: string
    default: ''


stages:

  - stage: Deploy_UAT
    displayName: Deploy UAT

    dependsOn:
      - Deploy_DEV

    condition: succeeded()

    jobs:

      - template: ../templates/deploy/azure-function-deploy.yml

        parameters:
          environmentName: '<AZURE-DEVOPS-ENVIRONMENT-UAT>'

          azureServiceConnection: '<AZURE-SERVICE-CONNECTION-UAT>'

          functionAppName: '<FUNCTION-APP-NAME-UAT>'

          artifactName: ${{ parameters.artifactName }}

          packageFileName: ${{ parameters.packageFileName }}

          appType: 'functionAppLinux'

          isFlexConsumption: false

          runSmokeTest: ${{ parameters.runSmokeTest }}

          smokeTestCommand: ${{ parameters.smokeTestCommand }}
