name: CD

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build release

    uses: ./.github/workflows/reusable-build.yml


  deploy-dev:
    name: Deploy DEV

    needs:
      - build

    uses: ./.github/workflows/reusable-deploy.yml

    with:
      environmentName: DEV


  deploy-uat:
    name: Deploy UAT

    needs:
      - deploy-dev

    uses: ./.github/workflows/reusable-deploy.yml

    with:
      environmentName: UAT


  deploy-stg:
    name: Deploy STG

    needs:
      - deploy-uat

    uses: ./.github/workflows/reusable-deploy.yml

    with:
      environmentName: STG


  deploy-prd:
    name: Deploy PRD

    needs:
      - deploy-stg

    uses: ./.github/workflows/reusable-deploy.yml

    with:
      environmentName: PRD
