name: Reusable - Deploy

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string


jobs:
  deploy:
    name: Deploy ${{ inputs.environmentName }}

    runs-on: self-hosted

    environment:
      name: ${{ inputs.environmentName }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v3

        with:
          name: function-app
          path: ${{ runner.temp }}/release


      - name: Login to Azure
        uses: azure/login@v3

        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}


      - name: Deploy Azure Function App
        uses: Azure/functions-action@v1

        with:
          app-name: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ runner.temp }}/release/function-app.zip
